### ISSUE TITLE
Tomate timer running twice faster

### ISSUE THREAD

**Issue by Artimi** [eliostvs/tomate#15]
Hello,
I've encountered strange behavior of tomate-gtk. Sometimes the time is running twice faster in pomodoro state. You can see it in the recorded [video](https://dl.dropboxusercontent.com/u/40268582/tomate-fast-1.ogv). This is quite severe bug if the main purpose of tomate is timer and it is done wrong.

**Comment by eliostvs** [comment]
Hi. Sorry for this trouble. I use gtk to schedule the time. Which distro do you use? Could you run tomate from the terminal with the parameter `-v` and post the output?

**Comment by Artimi** [comment]
Hi sorry for not replying. I'm running Ubuntu 16.04. When I run `tomate-gtk -v` I get following error:
```
ERROR:2017-03-15 12:55:13,564:tomate_gtk.main:Cannot find dependency u'dbus.session' for u'tomate.app' provider.
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/tomate_gtk/main.py", line 64, in main
    graph.validate()
  File "/usr/lib/python2.7/dist-packages/wiring/graph.py", line 356, in validate
    strongconnect(specification)
  File "/usr/lib/python2.7/dist-packages/wiring/graph.py", line 328, in strongconnect
    raise MissingDependencyError(specification, dependency)
MissingDependencyError: Cannot find dependency u'dbus.session' for u'tomate.app' provider.
Traceback (most recent call last):
  File "/usr/bin/tomate-gtk", line 9, in <module>
    load_entry_point('tomate-gtk==0.6.0', 'console_scripts', 'tomate-gtk')()
  File "/usr/lib/python2.7/dist-packages/tomate_gtk/main.py", line 74, in main
    six.reraise(*sys.exc_info())
  File "/usr/lib/python2.7/dist-packages/tomate_gtk/main.py", line 64, in main
    graph.validate()
  File "/usr/lib/python2.7/dist-packages/wiring/graph.py", line 356, in validate
    strongconnect(specification)
  File "/usr/lib/python2.7/dist-packages/wiring/graph.py", line 328, in strongconnect
    raise MissingDependencyError(specification, dependency)
wiring.graph.MissingDependencyError: Cannot find dependency u'dbus.session' for u'tomate.app' provider.
```
However I was able to replicate this problem:
1. You have pomodor in progress
2. Click stop
3. Immediately click run
4. Timer now ticks twice per second
Funny is that until you reach end of pomodoro you can do this as many times as you want and it will keep ticking faster and faster.

**Comment by vhquang** [comment]
Confirmed that I have the same issue Artimi has.

**Comment by eliostvs** [comment]
Sorry for the late response. In the last versions I did a bunch of small improvements that I hope fixed these bugs. If you still have problems, please open a new issue.
